name: module_kit_example_routes_list
description: Example using Route lists per module with module_kit.
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  module_kit:
    path: ../../
  go_router: any
  provider: any

flutter:
  uses-material-design: true
