name: module_kit_example_retry
description: Example showing retry flow with ModuleComposerBuilder errorBuilder.
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  module_kit:
    path: ../../
  go_router: any
  provider: any

flutter:
  uses-material-design: true
